name: Release

# This workflow is triggered manually
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Module cache setup
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: v1-npm-deps-${{ hashFiles('**/yarn.lock') }}
          restore-keys: v1-npm-deps-

      # Module installation
      - name: Install dependencies
        run: make install

      # The actual build
      - name: Build project
        run: make build

      # Publish to NPM [DRY RUN]
      - uses: JS-DevTools/npm-publish@v1
        with:
          package: ./dist/package.json
          token: ${{ secrets.NPM_TOKEN }}
          dry-run: true
          check-version: true

      # Some linting
      - name: Lint project
        run: make lint

      # Some testing
      - name: Test project
        run: make test

      # Some more testing
      - name: Test example projects
        run: make examples
