name: Release

# This workflow is triggered manually
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Module cache setup
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: v1-npm-deps-${{ hashFiles('**/yarn.lock') }}
          restore-keys: v1-npm-deps-

      # Module installation
      - name: Install dependencies
        run: make install

      # The actual build
      - name: Build project
        run: make build

      # Now let's store the build
      - name: Store build artefacts
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: dist

  publish:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: Public Github
      url: https://www.npmjs.com/package/ts-type-checked?activeTab=versions
    steps:
      # Get the build
      - name: Download the build
        uses: actions/download-artifact@v2
        with:
          name: build
          path: dist

      # Publish to NPM [DRY RUN]
      - uses: JS-DevTools/npm-publish@v1
        with:
          package: ./dist/package.json
          token: ${{ secrets.NPM_TOKEN }}
          check-version: true
