name: Test

# Controls when the action will run.
on:
  [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Module cache setup
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: v1-npm-deps-${{ hashFiles('**/yarn.lock') }}
          restore-keys: v1-npm-deps-

      # Module installation
      - name: Install dependencies
        run: make install

      # The actual build
      - name: Build project
        run: make build

      # Some linting
      - name: Lint project
        run: make lint

      # Now let's store the build
      - name: Store build artefacts
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: dist

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      # Module cache setup
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: v1-npm-deps-${{ hashFiles('**/yarn.lock') }}
          restore-keys: v1-npm-deps-

      # Get the build
      - name: Download the build
        uses: actions/download-artifact@v2
        with:
          name: build
          path: dist

      - name: Display structure of downloaded files
        run: ls -R

      # Test
      - name: Test
        run: make test

      # Test examples
      - name: Examples
        run: make examples
